### PR TITLE
Version 0.2

### LINKED ISSUE #1: The @provide/provided mechanism for optional interface functions.
What do we think of the @provide mechanism? That is the experimental/risky part of this package. Does anyone foresee big problems. Feel free to play around with it and see if it is intuitive.

### LINKED ISSUE #2: clone
I think it would be a good idea for each optional interface function to have an associated issue. I already put `clone` in the package, but I am definitely open to discussing it.

`clone(env)` will create a copy of the environment *at the current state*. A clone is assumed to be completely independent from the original environment from that point on.

Does anyone think it is a bad idea to add this as an optional interface function?

### LINKED ISSUE #8: valid_actions(env)
In e.g. MCTS it is often nice to get a list of a subset of actions that are valid in the environment. `validactions(env)` is an interface function that could provide such a list.

Should we add this as an optional interface function?

### LINKED ISSUE #10: observations(env)
Should we add `observations(env)` as an optional interface function to return the observation space?

### LINKED ISSUE #19: valid_actions_mask(env)
Related to https://github.com/JuliaReinforcementLearning/CommonRLInterface.jl/issues/8.

I suggest adding a `valid_actions_mask(env) :: BitVector` function that respects the following invariant:

```julia
valid_actions(env) = actions(env)[valid_actions_mask(env)]
```

I have found that when dealing with ML policies, this is often the most convenient way to access the set of valid actions.

For example, if `network` is a policy network that ends up with a softmax output and we want to pick an action based on the current state of the environment:

```julia
pi = network(get_state(env))
pi[.~valid_actions_mask(env)] = 0
pi ./= sum(pi)
action = actions(env)[rand(Categorical(pi))]
```

I do not see an easy and efficient way to emulate this pattern with only `actions` and `valid_actions`.

**Open question:** should we require that `valid_actions_mask` return a `BitVector` or should we allow anything that can be used to index an array (including a `Vector{Int}` enumerating the indices of valid actions)?

### LINKED ISSUE #21: render(env)
We should have a standard way of visualizing environments.

There are two ways to do visualizations in Julia - either use the [built in multimedia system](https://docs.julialang.org/en/v1/base/io-network/#Multimedia-I/O-1) or have a separate visualization pop up in an external window as in openai gym.

If we hook into the multimedia system, the visualization will display nicely in jupyter notebooks, IDEs like Juno, or popup windows through, e.g. ElectronDisplay. Moreover, it will be easy to save the frames to turn them into a gif or video or analyze them later.

I think the best way to integrate RL environments into the multimedia system is with a function called `render` that returns an object that is displayable (i.e. an object with a lot of [`show` methods](https://docs.julialang.org/en/v1/base/io-network/#Base.show-Tuple{Any,Any,Any}) such as a Plots.jl plot or a Compose.jl graphic or a graphic produced by Cairo, or a custom type (perhaps called something like `MyEnvVisualization`) with `show` methods implemented. Then, to display the visualization, someone would call [`display`](https://docs.julialang.org/en/v1/base/io-network/#Base.Multimedia.display)`(render(env))`.

Another option is to just have environment writers implement `show` for their environments directly, but I've found this is confusing, especially for people new to julia.

In order to wrap environments that call code in other languages that can pop up their own visualization windows, we may also want a different function, perhaps called `render_external(env)` that pops up a display window. `render_external` could easily be implemented with `render` using `render_external(env) = electrondisplay(render(env))`.

(Note that this is completely separate from the observation returned by `step!`, though they may use some of the same code if the observations are images.)

### PR DESCRIPTION
**Pull request by zsunberg**
Added `@provide` to fix #1 

Added the following functions
- `valid_actions` fixes #8 
- `clone` fixes #2 
- `observations` fixes #10 
- `valid_action_mask` fixes #19 
- `render` fixes #21 

I did not include `setstate!` #9 , yet, because there is still a question about whether we want that or `reset!(env, state)`.

I did not add `observe` #12 yet, because I don't understand the exact semantics of it. If someone can write a docstring for it that is unambiguous from both the environment writer and algorithm writer's perspective, then I think we could add it.

I did not set up Documenter.jl docs yet #24 , but I don't think this is necessary to be useful to release.

### CODE REVIEW

**Comment by zsunberg** [comment]
I'm requesting a couple of reviews, but if you want to review, please don't hesitate to jump in!

**Review by findmyway — APPROVED** [review]

**Comment by findmyway** [comment]
In https://github.com/JuliaReinforcementLearning/CommonRLInterface.jl/issues/20 @jonathan-laurent mentioned that some core common interfaces in single-agent and multi-agent environments can be contained here. So he may check it again in case some important functions are missing.

**Comment by jonathan-laurent** [comment]
I just made a [proposal](https://github.com/JuliaReinforcementLearning/CommonRLInterface.jl/issues/20#issuecomment-652449333) for supporting two-players, zero-sum games.

**Review by jbrea — APPROVED** [review]
I like this proposal!

**Comment by zsunberg** [comment]
OK, going to merge this but not going to register a new version. Will immediately start a PR with the changes discussed in #20 and #25

**Pull request merged**
